name: PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci

      - name: Build site
        if: github.event.action != 'closed'
        run: npm run build

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.6.2
        with:
          source-dir: dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
